config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  get 'welcome/index'
  get 'admin/index'
  get '/client', to: 'clients#index', as: '/client'

  resources :clients
  
  root 'welcome#index'

  resources :characters
  resources :rooms
  resources :items
  resources :areas
  resources :skills
  
end

app/models/character.rb
class Character < ApplicationRecord

  has_many :mobiles, dependent: :destroy
  has_many :rooms, through: :mobiles, class_name: "Room"

  has_many :inventory_items
  has_many :items, through: :inventory_items, class_name: "Item"

  has_one :equipment
  has_many :equipped, through: :equipment, class_name: "Item"

  has_many :character_skills
  has_many :skills, through: :character_skills

  belongs_to :created_by, class_name: "User"

  belongs_to :stat # weird, but since stat_id is on character, this is how it works...

  validates :name, presence: true, length: {minimum: 2}
  accepts_nested_attributes_for :stat, allow_destroy: true
  accepts_nested_attributes_for :inventory_items, allow_destroy: true
  accepts_nested_attributes_for :character_skills, allow_destroy: true
  accepts_nested_attributes_for :equipment
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  before_filter :authenticate_user!

  def new
    @character = Character.new
    @character.stat = Stat.new 
    @character.equipment = Equipment.new
    @character.char_class = "Thief"
    respond_to do |format|
      format.html { render :edit }
      format.json { render :show }
    end
  end

  def create
    if params[:id] && Character.exists?(params[:id].to_i)
      @character = Character.find(params[:id])
      @character.update(character_params)
    else
      @character = Character.new(character_params)
      @character.equipment = Equipment.create if @character.equipment.nil?
      @character.stat = Stat.create if @character.stat.nil?
      @character.update!(created_by: current_user)
    end
    if @character.save
      respond_to do |format|
        format.json { render :show }
        format.html
      end
    else
      redirect_to new_character_path
    end
  end

  def update
    @character = Character.find(params[:id])
     
    if @character.update(character_params)
      redirect_to @character
    else
      render 'edit'
    end
  end

  def show
    @character = Character.find(params[:id])
    respond_to do |format|
      format.json { render :show }
      format.html
    end
  end

  def edit
    if current_user.role == "immortal"
      @character = Character.find(params[:id])
    else
      flash[:error] = "You are not authorized to access this page."
      redirect_to root_path
    end
  end

  def index
    if current_user.role == 'immortal'
      @characters = Character.all
    else
      @characters = current_user.characters
    end

    respond_to do |format|
      format.json { render json: @characters }
      format.html
    end
  end

  def destroy
    @character = Character.find(params[:id])
    @character.destroy

    redirect_to characters_path
  end

  private

  def character_params
    params.permit(:id,
      :name,
      :short,
      :long,
      :keywords,
      :char_class,
      :description,  
      :stat_attributes => [:hitpoints, :manapoints, :attackspeed, :damagereduction, :damage, :hitroll],  
      :inventory_items_attributes => [:id, :_destroy, :item_id, :character_id],
      :equipment_attributes => [:weapon_id, :head_id],
      :character_skills_attributes => [:id, :skill_id, :character_id, :percentage]
      )
  end
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/views/characters/_form.html.erb
  <div class="input-group">
    <%= f.text_field :name, class: "form-control", placeholder: "Name..." %>
    <%= f.text_field :description, class: "form-control", placeholder: "Description..."  %>

		<%= f.fields_for :stat do |sf| %>
			<%= sf.number_field :hitpoints, class: "form-control", placeholder: "Hitpoints..." %>
			<%= sf.number_field :manapoints, class: "form-control", placeholder: "Manapoints..." %>
			<%= sf.number_field :attackspeed, class: "form-control", placeholder: "Attackspeed..." %>
			<%= sf.number_field :damagereduction, class: "form-control", placeholder: "Damagereduction..." %>
		<% end %>

    <%= f.submit "Save" , class: "form-control"  %>
  </div>

app/views/characters/edit.html.erb
<div class="row" ng-controller="editCharacter">
  <div class="col-sm-6">
    <div class="panel panel-default">
    	<div class="panel-heading">
    		<h2>Edit <%= @character.name %></h2>
    	</div>
    	<div class="panel-body">
              <h3 class="text-center">Name</h3>
              <input type="text" ng-model="character.name" class="form-control">

              <h3 class="text-center">Short</h3>
              <input type="text" ng-model="character.short" class="form-control">

              <h3 class="text-center">Long</h3>
              <input type="text" ng-model="character.long" class="form-control">

              <h3 class="text-center">Keywords</h3>
              <input type="text" ng-model="character.keywords" class="form-control">

            <!-- admin always have access to class options -->

              <h3 for="" class="text-center">Class</h3>
            <% if current_user.role == "immortal" %>
              <select ng-model="character.char_class" ng-options="o for o in [null, 'Thief']"></select>
            <% else %>
              <!-- show class select on NEW character only -->
              <select class="form-control" ng-show="!character.id" ng-model="character.char_class" ng-options="o for o in ['Thief']"></select>
              <span ng-show="character.id">{{ character.char_class }}</span>
            <% end %>

              <h3 for="" class="text-center">Description</h3>
              <input type="text" class="form-control" ng-model="character.description">
            <!-- stats, inventory and equipment are not settable by players, should have defaults -->
            <% if current_user.role == "immortal" %>
            <label for="" class="control-label">Stats</label>
            <table>
              <tbody>
                <tr ng-repeat="(k, v) in character.stat track by $index">
                  <th>{{ k }}</th>
                  <td><input type="number" ng-model="character.stat[k]"></td>
                </tr>
              </tbody>
            </table>
            <br>
            <label for="" class="control-label">Inventory</label>
            <div ng-repeat="inventory_item in character.inventory_items" class="input-group">
              <select name="" id="" ng-model="inventory_item.item_id" class="form-control" ng-options="item.id as item.name for item in items"></select>
              <span class="input-group-btn" ng-click="destroy(inventory_item);">
                <span class="btn btn-default" ng-class="{'btn-danger' : inventory_item._destroy}">
                  <span class="glyphicon glyphicon-remove"></span>
                </span>
              </span>
            </div>
            <span class="btn btn-primary" ng-click="add(character.inventory_items);">Add Item</span>
            <br>

            <label for="" class="control-label">Equipment</label>
            <div ng-repeat="(slot, item) in character.equipment track by $index" class="input-group">
              <label for="" class="control-label">{{ slot }}</label>
              <select name="" id="" ng-model="character.equipment[slot]" class="form-control" ng-options="item.id as item.name for item in items"></select>
            </div><br>
            <% end %>

            <!-- only accessible to immortals and new character creation screen -->
            <h3 class="text-center">
              Skills
              <br>
              <small>
                <strong>Creation Points:</strong> {{ creationPoints() }}
              </small>
            </h3>
            <% if current_user.role == "immortal" || !@character.id %>
              <ul class="list-group skills-list" ui-sortable="sortableOptions" ng-model="character.skills">
                <li class='list-group-item' ng-if="character.skills.length <= 0">Drag skills here to add them to your character.</li>
                <li class='list-group-item skill' ng-repeat="skill in character.skills">
                  <h4 class="list-group-item-heading">{{ skill.name }}</h4>
                  <p class="list-group-item-body">
                    <strong>Level:</strong> {{ skill.level }}
                    <strong>Creation Points:</strong> {{ skill.cp }}
                  </p>
                </li>
              </ul>
            <% else %>
            <ul class="list-group">
              <li class="list-group-item text-center" ng-repeat="skill in character.skills">
                <h4 class="list-group-item-heading">{{ skill.name }}</h4>
                <p class="list-group-item-body">
                  <strong>Level:</strong> {{ skill.level }}
                  <strong>Creation Points:</strong> {{ skill.cp }}
                </p>
              </li>
            </ul>  
            <% end %>
    	</div>
      <div class="panel-footer">
          <div class="panel-footer"><span class="btn btn-default" ng-click="save();">Save</span></div>
      </div>
    </div>
    <input type="hidden" value="<%= @character.id %>" id="characterId">
  </div>
  <% if current_user.role == "immortal" || !@character.id %>
    <div class="col-sm-6">
      <h3>Skills</h3>
      <ul class='list-group skills-list' ui-sortable="sortableOptions" ng-model="skills">
        <li class='list-group-item skill' ng-repeat="skill in skills track by $index">
          <h4 class="list-group-item-heading">{{ skill.name }}</h4>
          <p class="list-group-item-body">
            <strong>Level:</strong> {{ skill.level }}
            <strong>Creation Points:</strong> {{ skill.cp }}
          </p>
        </li>
        <li class='list-group-item text-warning'>Drag skills back here to remove them from your character.</li>
      </div>
    </div>
  <% end %>
</div>

app/views/characters/index.html.erb
<div class="row">
  <div class="col-sm-12">
    <ul class="list-group">
      <li class="list-group-item text-right">
        <a href="/characters/new" class="btn btn-primary"><span class="glyphicon glyphicon-plus"></span> Add New</a>
      </li>
      <% @characters.each do |character| %>
        <li class="list-group-item">
          <div class="row">
            <div class="col-sm-6"><span class='h3'><%= character.name %></span></div>
            <div class="col-sm-6 text-right">
              <%= link_to 'Play', client_path(play: character.id), class: "btn btn-default", disabled: current_user.active.present? %>
              <a href="<%= character_path(character) %>" class="btn btn-info">See more</a>
              <% if current_user.role == "immortal" %>
                <a href="<%= edit_character_path(character) %>" class="btn btn-success">Edit</a>
                <%= link_to 'Delete', character_path(character), method: :delete, class: 'btn btn-danger' %>
              <% end %>
              <!--<a href="<%= character_path(character) %>/destroy" class="btn btn-danger">Delete</a>-->
            </div>
          </div>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/characters/new.html.erb
<h1>New Character</h1>
<%= form_for :character, url: characters_path do |f| %>
	<%= f.select :class, [nil, "Thief"], {}, {class: 'form-control'} %>
	<%= render partial: "shared/form", locals: {f: f} %>
<% end %>

app/views/characters/show.html.erb
<div class="row">
  <div class="col-sm-6">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h1><%= @character.name %></h1>
      </div>
      <div class="panel-body">
        <p><%= @character.description %></p>
        <ul class="list-inline">
          <li class="h4">This character appears in the following rooms:</li>
          <% @character.rooms.each do |room| %>
            <li><%= link_to room.name, room_path(room) %></li>
          <% end %>
        </ul>
        <%= render partial: "shared/show_stats", locals: {stats: @character.stat} %> 
        <%= link_to "Edit", edit_character_path(@character), class: 'btn btn-success' %>
      </div>
    </div>
  </div>
  <div class="col-sm-6">
    <ul class="list-group">
      <li class="list-group-item">
        <h1 class="list-group-item-heading">Inventory</h1>
      </li>
      <% @character.items.each do |item| %>
      <li class="list-group-item">
        <h4 class="list-group-item-heading"><%= item.name %></h4>
      </li>
      <% end %>
    </ul>
    <ul class="list-group">
      <li class="list-group-item">
        <h1 class="list-group-item-heading">Equipment</h1>
      </li>
      <% @character.equipment.display_value.each do |slot, item| %>
      <li class="list-group-item">
        <h4 class="list-group-item-heading"><strong><%= slot.to_s.humanize %>:</strong> <%= item ? item.name : "Nothing" %></h4>
      </li>
      <% end %>
    </ul>
    <ul class="list-group">
      <li class="list-group-item">
        <h1 class="list-group-item-heading">Skills</h1>
      </li>
      <% @character.skills.each do |skill| %>
      <li class="list-group-item">
        <h3 class="list-group-item-heading"><%= skill.name %></h3>
      </li>
      <% end %>
    </ul>
  </div>
</div>