config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  get 'welcome/index'
  get 'admin/index'
  get '/client', to: 'clients#index', as: '/client'

  resources :clients
  
  root 'welcome#index'

  resources :characters
  resources :rooms
  resources :items
  resources :areas
  resources :skills
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/area.rb
class Area < ApplicationRecord
  has_many :rooms
end

app/models/character.rb
class Character < ApplicationRecord

  has_many :mobiles, dependent: :destroy
  has_many :rooms, through: :mobiles, class_name: "Room"

  has_many :inventory_items
  has_many :items, through: :inventory_items, class_name: "Item"

  has_one :equipment
  has_many :equipped, through: :equipment, class_name: "Item"

  has_many :character_skills
  has_many :skills, through: :character_skills

  belongs_to :created_by, class_name: "User"

  belongs_to :stat # weird, but since stat_id is on character, this is how it works...

  validates :name, presence: true, length: {minimum: 2}
  accepts_nested_attributes_for :stat, allow_destroy: true
  accepts_nested_attributes_for :inventory_items, allow_destroy: true
  accepts_nested_attributes_for :character_skills, allow_destroy: true
  accepts_nested_attributes_for :equipment
end

app/models/character_skill.rb
class CharacterSkill < ApplicationRecord
	belongs_to :skill
	belongs_to :character
end

app/models/equipment.rb
class Equipment < ApplicationRecord
	belongs_to :character
	belongs_to :weapon, class_name: "Item"
	belongs_to :head, class_name: "Item"

	def show
		{
			weapon_id: weapon ? weapon.id : nil,
			head_id: head ? head.id : nil
		}
	end

  def display_value
    {
      weapon: weapon,
      head: head
    }
  end
end

app/models/exit.rb
class Exit < ApplicationRecord
	belongs_to :room
	belongs_to :destination, class_name: "Room"
end

app/models/inventory_item.rb
class InventoryItem < ApplicationRecord
	belongs_to :character
	belongs_to :item
end

app/models/item.rb
class Item < ApplicationRecord
	
	belongs_to :stat
  accepts_nested_attributes_for :stat, allow_destroy: true

  has_many :room_items
  has_many :rooms, through: :room_items, class_name: "Room"

  has_many :inventory_items
  has_many :characters, through: :inventory_items, class_name: "Character"

  has_many :equipments
  has_many :characters, through: :equipments

end

app/models/mobile.rb
class Mobile < ApplicationRecord
  belongs_to :character, class_name: "Character"
  belongs_to :room, class_name: "Room"
  belongs_to :user, class_name: "User"
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :mobiles, dependent: :destroy
  has_many :characters, through: :mobiles, class_name: "Character"

  has_many :exits
  has_many :rooms, through: :exits, foreign_key: :destination, class_name: "Room"

  has_many :room_items
  has_many :items, through: :room_items, class_name: "Item"

  belongs_to :area

  accepts_nested_attributes_for :room_items, allow_destroy: true
  accepts_nested_attributes_for :mobiles, allow_destroy: true
  accepts_nested_attributes_for :exits, allow_destroy: true

end

app/models/room_item.rb
class RoomItem < ApplicationRecord
	belongs_to :room
	belongs_to :item
end

app/models/skill.rb
class Skill < ApplicationRecord
end

app/models/stat.rb
class Stat < ApplicationRecord
	def show
		{
			hitpoints: hitpoints,
			manapoints: manapoints,
			attackspeed: attackspeed,
			damagereduction: damagereduction,
      damage: damage,
      hitroll: hitroll
		}
	end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :characters, foreign_key: :created_by_id
  has_many :player_characters, class_name: "Mobile"
  belongs_to :active, class_name: "Mobile"

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
  end
end

app/controllers/areas_controller.rb
class AreasController < ApplicationController

  def index
    render json: Area.all
  end

  def new
    @area = Area.new
  end

  def create
    @area = Area.create(area_params)
    redirect_to rooms_path(area: @area.id)
  end

  private

  def area_params
    params.require(:area).permit(:name)
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_filter :authenticate_user!

  def new
    @item = Item.new
    @item.stat = Stat.new
  end

  def edit
    @item = Item.find(params[:id])
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to @item
    else
      redirect_to new_item_path
    end
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
  end

  def index
  	@items = Item.all
    respond_to do |format|
      format.json { render json: @items }
      format.html
    end
  end

  def show
  	@item = Item.find(params[:id])
  end

  private

  def item_params
  	params.require(:item).permit(:name, :description, :slot, :level, :noun, :stat_attributes => [:hitpoints, :manapoints, :attackspeed, :damagereduction, :damage, :hitroll])
  end

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_filter :authenticate_user!

  def new
    @room = Room.new
    render :edit
    #redirect_to edit_room_path
  end

  def create
    if params[:id] && Room.exists?(params[:id].to_i)
      @room = Room.find(params[:id])
      @room.update(room_params)
    else
      @room = Room.new(room_params)
    end
    if @room.save
      respond_to do |format|
        format.json { render :show }
        format.html
      end
    else
      redirect_to new_room_path
    end
  end

  def update
    @room = Room.find(params[:id])
     
    if @room.update(room_params)
      redirect_to @room
    else
      render 'edit'
    end
  end

  def show
    @room = Room.find(params[:id])
    @mobiles = @room.mobiles
    respond_to do |format|
      format.json { render :show }
      format.html
    end
  end

  def edit
    @room = Room.find(params[:id])
  end
  
  def destroy
    @room = Room.find(params[:id])
    @room.destroy

    redirect_to rooms_path
  end

  def index
    if params[:area_id]
      @area_name = Area.exists?(params[:area_id]) ? Area.find(params[:area_id]).name : "Invalid Area"
      @rooms = Room.where(area_id: params[:area_id])
    else
      @rooms = Room.all
    end

    respond_to do |format|
      format.json { render json: @rooms }
      format.html
    end
  end

  private

  def room_params
    params.permit(:name, :description, :area_id,
      mobiles_attributes: [:id, :character_id, :room_id, :_destroy], 
      exits_attributes: [:id, :room_id, :destination_id, :direction, :_destroy],
      room_items_attributes: [:id, :room_id, :item_id, :_destroy] )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def indefinite_article(word)
    %w(a e i o u).include?(word[0].downcase) ? "an #{word}" : "a #{word}"
	end

end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/areas/new.html.erb
<div class="row">
  <div class="col-sm-5">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h1>New Area</h1>
      </div>
      <div class="panel-body">
        <%= form_for @area do |f| %>
          <label for="" class="control-label">Name</label>
          <%= f.text_field :name, class: "form-control" %>
          <%= f.submit :save, class: "form-control" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/items/_form.html.erb
  <div class="input-group">
    <%= f.text_field :name, class: "form-control", placeholder: "Name..." %>
    <%= f.text_field :description, class: "form-control", placeholder: "Description..."  %>

    <%= f.select :slot, ["head", "weapon"], {}, {class: "form-control"} %>
    <%= f.text_field :noun, class: "form-control", placeholder: "Noun..." %>
    <%= f.number_field :level, class: "form-control", placeholder: "Level..." %>

		<%= f.fields_for :stat do |sf| %>
			<%= sf.number_field :hitpoints, class: "form-control", placeholder: "Hitpoints..." %>
			<%= sf.number_field :manapoints, class: "form-control", placeholder: "Manapoints..." %>
			<%= sf.number_field :attackspeed, class: "form-control", placeholder: "Attackspeed..." %>
			<%= sf.number_field :damagereduction, class: "form-control", placeholder: "Damagereduction..." %>
      <%= sf.number_field :damage, class: "form-control", placeholder: "Damage..." %>
      <%= sf.number_field :hitroll, class: "form-control", placeholder: "Hitroll..." %>
		<% end %>

    <%= f.submit "Save" , class: "form-control"  %>
  </div>

app/views/items/edit.html.erb
<h1>Edit Item</h1>
<%= form_for @item, url: item_path(@item), method: :patch do |f| %>
  <div class="input-group">
		<%= render partial: "form", locals: {f: f} %>
  </div>
<% end %>

app/views/items/index.html.erb
<div class="row">
  <div class="col-sm-12">
    <ul class="list-group">
      <li class="list-group-item text-right">
        <a href="/items/new" class="btn btn-primary"><span class="glyphicon glyphicon-plus"></span> Add New</a>
      </li>
      <% @items.each do |item| %>
        <li class="list-group-item">
          <div class="row">
            <div class="col-sm-6"><span class='h3'><%= item.name %></span></div>
            <div class="col-sm-6 text-right">
              <a href="<%= item_path(item) %>" class="btn btn-info">See more</a>
              <a href="<%= edit_item_path(item) %>" class="btn btn-success">Edit</a>
              <%= link_to 'Delete', item_path(item), method: :delete, class: 'btn btn-danger' %>
              <!--<a href="<%= item_path(item) %>/destroy" class="btn btn-danger">Delete</a>-->
            </div>
          </div>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/items/new.html.erb
<h1>New Item</h1>
<%= form_for @item, url: items_path do |f| %>
	<%= render partial: "form", locals: {f: f} %>
<% end %>

app/views/items/show.html.erb
<h1><%= @item.name %></h1>
<p><%= @item.description %></p>
<ul class="list-inline">
  <li class="h4">This item appears in the following rooms:</li>
  <% @item.rooms.each do |room| %>
    <li><%= link_to room.name, room_path(room) %></li>
  <% end %>
</ul>
<%= render partial: "shared/show_stats", locals: {stats: @item.stat} %> 
<%= link_to "Edit", edit_item_path(@item), class: 'btn btn-success' %>