config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  get 'welcome/index'
  get 'admin/index'
  get '/client', to: 'clients#index', as: '/client'

  resources :clients
  
  root 'welcome#index'

  resources :characters
  resources :rooms
  resources :items
  resources :areas
  resources :skills
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/area.rb
class Area < ApplicationRecord
  has_many :rooms
end

app/models/character.rb
class Character < ApplicationRecord

  has_many :mobiles, dependent: :destroy
  has_many :rooms, through: :mobiles, class_name: "Room"

  has_many :inventory_items
  has_many :items, through: :inventory_items, class_name: "Item"

  has_one :equipment
  has_many :equipped, through: :equipment, class_name: "Item"

  has_many :character_skills
  has_many :skills, through: :character_skills

  belongs_to :created_by, class_name: "User"

  belongs_to :stat # weird, but since stat_id is on character, this is how it works...

  validates :name, presence: true, length: {minimum: 2}
  accepts_nested_attributes_for :stat, allow_destroy: true
  accepts_nested_attributes_for :inventory_items, allow_destroy: true
  accepts_nested_attributes_for :character_skills, allow_destroy: true
  accepts_nested_attributes_for :equipment
end

app/models/character_skill.rb
class CharacterSkill < ApplicationRecord
	belongs_to :skill
	belongs_to :character
end

app/models/equipment.rb
class Equipment < ApplicationRecord
	belongs_to :character
	belongs_to :weapon, class_name: "Item"
	belongs_to :head, class_name: "Item"

	def show
		{
			weapon_id: weapon ? weapon.id : nil,
			head_id: head ? head.id : nil
		}
	end

  def display_value
    {
      weapon: weapon,
      head: head
    }
  end
end

app/models/exit.rb
class Exit < ApplicationRecord
	belongs_to :room
	belongs_to :destination, class_name: "Room"
end

app/models/inventory_item.rb
class InventoryItem < ApplicationRecord
	belongs_to :character
	belongs_to :item
end

app/models/item.rb
class Item < ApplicationRecord
	
	belongs_to :stat
  accepts_nested_attributes_for :stat, allow_destroy: true

  has_many :room_items
  has_many :rooms, through: :room_items, class_name: "Room"

  has_many :inventory_items
  has_many :characters, through: :inventory_items, class_name: "Character"

  has_many :equipments
  has_many :characters, through: :equipments

end

app/models/mobile.rb
class Mobile < ApplicationRecord
  belongs_to :character, class_name: "Character"
  belongs_to :room, class_name: "Room"
  belongs_to :user, class_name: "User"
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :mobiles, dependent: :destroy
  has_many :characters, through: :mobiles, class_name: "Character"

  has_many :exits
  has_many :rooms, through: :exits, foreign_key: :destination, class_name: "Room"

  has_many :room_items
  has_many :items, through: :room_items, class_name: "Item"

  belongs_to :area

  accepts_nested_attributes_for :room_items, allow_destroy: true
  accepts_nested_attributes_for :mobiles, allow_destroy: true
  accepts_nested_attributes_for :exits, allow_destroy: true

end

app/models/room_item.rb
class RoomItem < ApplicationRecord
	belongs_to :room
	belongs_to :item
end

app/models/skill.rb
class Skill < ApplicationRecord
end

app/models/stat.rb
class Stat < ApplicationRecord
	def show
		{
			hitpoints: hitpoints,
			manapoints: manapoints,
			attackspeed: attackspeed,
			damagereduction: damagereduction,
      damage: damage,
      hitroll: hitroll
		}
	end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :characters, foreign_key: :created_by_id
  has_many :player_characters, class_name: "Mobile"
  belongs_to :active, class_name: "Mobile"

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
  end
end

app/controllers/areas_controller.rb
class AreasController < ApplicationController

  def index
    render json: Area.all
  end

  def new
    @area = Area.new
  end

  def create
    @area = Area.create(area_params)
    redirect_to rooms_path(area: @area.id)
  end

  private

  def area_params
    params.require(:area).permit(:name)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

	def indefinite_article(word)
    %w(a e i o u).include?(word[0].downcase) ? "an #{word}" : "a #{word}"
	end

end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/nav/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header"><%= link_to "Redemption on Rails", root_path, class: "navbar-brand" %></div>
    <ul class="nav navbar-nav">
      <li><%= link_to "Characters", characters_path %></li>
      <li><%= link_to "Rooms", rooms_path %></li>
      <li><%= link_to "Items", items_path %></li>
      <li>
				<% if current_user %>
	      	<%= link_to "Logout", destroy_user_session_path, method: :delete %>
	      <% else %>
				  <%= link_to('Login', new_user_session_path)  %>
	      <% end %>
      </li>
      <li class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#">Areas
        <span class="caret"></span></a>
        <ul class="dropdown-menu">
          <% Area.all.each do |area| %>
            <li><%= link_to area.name, rooms_path(area_id: area.id) %></li>
          <% end %>
          <li><%= link_to "+ New", new_area_path %></li>
        </ul>
      </li>
      <li><%= link_to "Skills", skills_path %></li>
    </ul>
  </div>
</nav>

app/views/shared/_form.html.erb
  <div class="input-group">
    <%= f.text_field :name, class: "form-control", placeholder: "Name..." %>
    <%= f.text_field :description, class: "form-control", placeholder: "Description..."  %>

		<%= f.fields_for :stat do |sf| %>
			<%= sf.number_field :hitpoints, class: "form-control", placeholder: "Hitpoints..." %>
			<%= sf.number_field :manapoints, class: "form-control", placeholder: "Manapoints..." %>
			<%= sf.number_field :attackspeed, class: "form-control", placeholder: "Attackspeed..." %>
			<%= sf.number_field :damagereduction, class: "form-control", placeholder: "Damagereduction..." %>
		<% end %>

    <%= f.submit "Save" , class: "form-control"  %>
  </div>

app/views/shared/_show_stats.html.erb
<table class="table table-bordered table-hover">
	<thead>
		<tr>
			<th colspan="2"><h4>Stats</h4></th>
		</tr>
	</thead>
	<tbody>
		<% stats.show.each do |k, v| %>
			<tr>
				<th><%= k.to_s.humanize %></th>
				<td><%= v %></td>
			</tr>
		<% end %>		
	</tbody>
</table>